# Generated by Django 6.1.1 on 2026-09-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_photo_public_id_property_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Casa', 'Casas'), ('Apartamento', 'Apartamentos'), ('Aparta estudio', 'Aparta estudios'), ('Oficina', 'Oficina'), ('Bodega', 'Bodega'), ('Local', 'Locales')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateField(),
        ),
    ]
