# Generated by Django 6.1.1 on 2026-09-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_document_number_property_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='document_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Casa', 'Casas'), ('Apartamento', 'Apartamentos'), ('Aparta estudio', 'Aparta estudios'), ('Oficina', 'Oficina'), ('Bodega', 'Bodega'), ('Local', 'Locales')], max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='tenant_email',
            field=models.EmailField(max_length=254),
        ),
    ]
