# Generated by Django 6.1.1 on 2026-09-11 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitemphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('public_id', models.CharField(max_length=255)),
                ('secure_url', models.URLField(max_length=500)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='inventory.inventory')),
            ],
        ),
    ]
