# Generated by Django 6.1.1 on 2026-09-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorysignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(blank=True, choices=[('good', 'Buen estado'), ('regular', 'Regular'), ('bad', 'Mal estado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='type_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
