# Generated by Django 6.1.1 on 2026-09-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_item_type_inventoryitem_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Característica de inventario', 'verbose_name_plural': 'Características de inventario'},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos adicionales'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo o material'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(blank=True, choices=[('good', 'Buen estado'), ('regular', 'Regular'), ('bad', 'Mal estado')], max_length=20, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='type_options',
            field=models.JSONField(blank=True, default=list, verbose_name='Opciones de tipo o material'),
        ),
    ]
