# Generated by Django 6.1.1 on 2026-09-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventoryitem_options_inventoryitem_extra_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_description',
            field=models.BooleanField(default=False, verbose_name='Es descripción adicional'),
        ),
    ]
